### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by tuwonga** [KnoBuddy/VisualDiffusion#23]
**Describe the bug**
When I try to set ETA : 0.8 I have an error

**To Reproduce**
` Traceback (most recent call last):
  File "prd.py", line 2125, in <module>
    do_run(batch_image)
  File "prd.py", line 1127, in do_run
    samples = do_sample_fn(init, args.steps - cur_t - 1)
  File "prd.py", line 1100, in do_sample_fn
    eta=eta,`

**Desktop (please complete the following information):**
 - OS: WINDOWS 11
 - GPU and VRAM: NVIDIA RTX3060Ti 8GB
 - CUDA Version 11.7

**Additional context**
Thank you

**Comment by KnoBuddy** [comment]
I believe this is the same issue as you asked about with clamp max. Both are schedules. I haven't used PRD in over a month, unless something's changed there isn't many bugs I was aware of and the ones there are shouldn't occur within normal operation of PRD. And since you are getting a PRD error it could be Visual Diffusion giving PRD bad settings, or it could be that it just passed on your bad settings and PRD is erroring out.

**Comment by KnoBuddy** [comment]
If you post your gui_settings file maybe I can be more helpful.

**Comment by KnoBuddy** [comment]
Also are you 100* certain that's the whole error?

**Comment by tuwonga** [comment]
> Also are you 100* certain that's the whole error?

`Traceback (most recent call last):
  File "prd.py", line 2125, in <module>
    do_run(batch_image)
  File "prd.py", line 1127, in do_run
    samples = do_sample_fn(init, args.steps - cur_t - 1)
  File "prd.py", line 1100, in do_sample_fn
    eta=eta,
NameError: name 'eta' is not defined`

I have no more errors

**Comment by tuwonga** [comment]
Sorry, I forgot 'eta' is not defined

**Comment by wcarletsdrive** [comment]
I have eta is not defined error too if I change the eta and clamp max.

**Comment by tuwonga** [comment]
> Sorry, I forgot 'eta' is not defined

I think you can't change eta

**Comment by KnoBuddy** [comment]
> I have eta is not defined error too if I change the eta and clamp max.

Are you using PRS, or PRD? I will assume PRD in which case, if you want to change clamp_max and eta from auto, you must format the value as a schedule as seen in the fields to the right in this picture.

![image](https://user-images.githubusercontent.com/64171756/196005789-571b158b-4049-4b80-af21-ca21102ef96b.png)

The total must add up to 1000, if you would like a single value to use the whole way through you can do something like [XX]*1000, where XX is some number you want to use. Otherwise if you do [XX]*400+[YY]*600 which would use XX value for the first 40% of the render, and YY for the second 60% of the render.

**Comment by wcarletsdrive** [comment]
I use PRD: Hey thanks for the quick reply, so I copied the format of cut ic pow over to clamp max and I got an error before saying “could not convert string to float integer”. Can you tell me what format works for you in there and for eta? And when I enter in the prompt replacing the default prompt, it’s completely different than it should actually be. (I know this from disco diffusion on colab)
